name: Deploy Documentation

on: 
  workflow_run:
    workflows: [build-test]
    branches: [master]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: NPM Install
        run: npm install

      - name: Build Docs
        run: npm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/build/arcgis-rest-js # The folder the action should deploy.